spring.application.name=Primeira-aplicacao-spring
#aqui eu possso trocar a porta que esta roando meu projeto
server.port=3000
#isso fala que o properties que vai ser usado e o outro
spring.profiles.active=Dev
